require("haekyu.plugins-setup")

require("haekyu.core.colorscheme")
require("haekyu.core.options")
require("haekyu.core.keymaps")

require("haekyu.plugins.nvim-tree")
require("haekyu.plugins.todo-comments")
require("haekyu.plugins.lualine")
require("haekyu.plugins.telescope")
require("haekyu.plugins.nvim-cmp")
require("haekyu.plugins.lsp.mason")
require("haekyu.plugins.lsp.lspsaga")
require("haekyu.plugins.lsp.lspconfig")
require("haekyu.plugins.lsp.null-ls")
require("haekyu.plugins.autopairs")
require("haekyu.plugins.treesitter")
require("haekyu.plugins.gitsigns")
require("haekyu.plugins.bufferline")
--require("haekyu.plugins.shade")
require("haekyu.plugins.ccc")
require("haekyu.plugins.dashboard-nvim")
require("haekyu.plugins.nvim-notify")
require("haekyu.plugins.comment")
require("haekyu.plugins.markdown")
